spring.application.name=News Aggregator App
spring.datasource.url=jdbc:postgresql://localhost:5432/news_aggregation_db
spring.datasource.username=postgres
spring.datasource.password=hello
spring.datasource.driver-class-name=org.postgresql.Driver

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=javalearner47@gmail.com
spring.mail.password=ubdamwqgecwhxspe
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect